//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceFlightstats.ArlinesV1SoapService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/")]
    public partial class APIException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorIdField;
        
        private int httpStatusCodeField;
        
        private bool httpStatusCodeFieldSpecified;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorId {
            get {
                return this.errorIdField;
            }
            set {
                this.errorIdField = value;
                this.RaisePropertyChanged("errorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int httpStatusCode {
            get {
                return this.httpStatusCodeField;
            }
            set {
                this.httpStatusCodeField = value;
                this.RaisePropertyChanged("httpStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool httpStatusCodeSpecified {
            get {
                return this.httpStatusCodeFieldSpecified;
            }
            set {
                this.httpStatusCodeFieldSpecified = value;
                this.RaisePropertyChanged("httpStatusCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/")]
    public partial class airline : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fsField;
        
        private string iataField;
        
        private string icaoField;
        
        private string nameField;
        
        private string phoneNumberField;
        
        private bool activeField;
        
        private string dateFromField;
        
        private string dateToField;
        
        private string categoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fs {
            get {
                return this.fsField;
            }
            set {
                this.fsField = value;
                this.RaisePropertyChanged("fs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iata {
            get {
                return this.iataField;
            }
            set {
                this.iataField = value;
                this.RaisePropertyChanged("iata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icao {
            get {
                return this.icaoField;
            }
            set {
                this.icaoField = value;
                this.RaisePropertyChanged("icao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("active");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
                this.RaisePropertyChanged("dateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
                this.RaisePropertyChanged("dateTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
                this.RaisePropertyChanged("category");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", ConfigurationName="ArlinesV1SoapService.airlinesService")]
    public interface airlinesService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByIcaoRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByIcaoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByIcao/Fault/AP" +
            "IException", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcaoResponse airlineByIcao(WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByIcaoRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByIcaoResponse")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcaoResponse> airlineByIcaoAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIata/Fault/A" +
            "PIException", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataResponse airlinesByIata(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataResponse" +
            "")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataResponse> airlinesByIataAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByFsCodeRequest" +
            "", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByFsCodeRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByFsCode/Fault/" +
            "APIException", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCodeResponse airlineByFsCode(WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByFsCodeRequest" +
            "", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlineByFsCodeRespons" +
            "e")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCodeResponse> airlineByFsCodeAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIcaoRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIcaoResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIcao/Fault/A" +
            "PIException", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcaoResponse airlinesByIcao(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIcaoRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIcaoResponse" +
            "")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcaoResponse> airlinesByIcaoAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/currentAirlinesRequest" +
            "", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/currentAirlinesRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/currentAirlines/Fault/" +
            "APIException", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.currentAirlinesResponse currentAirlines(WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/currentAirlinesRequest" +
            "", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/currentAirlinesRespons" +
            "e")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.currentAirlinesResponse> currentAirlinesAsync(WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/allAirlinesRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/allAirlinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/allAirlines/Fault/APIE" +
            "xception", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.allAirlinesResponse allAirlines(WcfServiceFlightstats.ArlinesV1SoapService.allAirlines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/allAirlinesRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/allAirlinesResponse")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.allAirlinesResponse> allAirlinesAsync(WcfServiceFlightstats.ArlinesV1SoapService.allAirlines request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlines/Fault/APIExce" +
            "ption", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesResponse airlines(WcfServiceFlightstats.ArlinesV1SoapService.airlines request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesRequest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesResponse")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesResponse> airlinesAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlines request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataForDateR" +
            "equest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataForDateR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WcfServiceFlightstats.ArlinesV1SoapService.APIException), Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataForDate/" +
            "Fault/APIException", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDateResponse airlinesByIataForDate(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataForDateR" +
            "equest", ReplyAction="http://v1.airlines.cache.conducivetech.com/airlinesService/airlinesByIataForDateR" +
            "esponse")]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDateResponse> airlinesByIataForDateAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlineByIcao", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlineByIcao {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icaoCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int day;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public airlineByIcao() {
        }
        
        public airlineByIcao(string appId, string appKey, string icaoCode, int year, int month, int day, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.icaoCode = icaoCode;
            this.year = year;
            this.month = month;
            this.day = day;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlineByIcaoResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlineByIcaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public airlineByIcaoResponse() {
        }
        
        public airlineByIcaoResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesByIata", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesByIata {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iataCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public airlinesByIata() {
        }
        
        public airlinesByIata(string appId, string appKey, string iataCode, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.iataCode = iataCode;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesByIataResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesByIataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public airlinesByIataResponse() {
        }
        
        public airlinesByIataResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlineByFsCode", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlineByFsCode {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public airlineByFsCode() {
        }
        
        public airlineByFsCode(string appId, string appKey, string code, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.code = code;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlineByFsCodeResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlineByFsCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public airlineByFsCodeResponse() {
        }
        
        public airlineByFsCodeResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesByIcao", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesByIcao {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string icaoCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public airlinesByIcao() {
        }
        
        public airlinesByIcao(string appId, string appKey, string icaoCode, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.icaoCode = icaoCode;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesByIcaoResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesByIcaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public airlinesByIcaoResponse() {
        }
        
        public airlinesByIcaoResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="currentAirlines", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class currentAirlines {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public currentAirlines() {
        }
        
        public currentAirlines(string appId, string appKey, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="currentAirlinesResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class currentAirlinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public currentAirlinesResponse() {
        }
        
        public currentAirlinesResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="allAirlines", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class allAirlines {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public allAirlines() {
        }
        
        public allAirlines(string appId, string appKey, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="allAirlinesResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class allAirlinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public allAirlinesResponse() {
        }
        
        public allAirlinesResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlines", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlines {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int day;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public airlines() {
        }
        
        public airlines(string appId, string appKey, int year, int month, int day, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.year = year;
            this.month = month;
            this.day = day;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public airlinesResponse() {
        }
        
        public airlinesResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesByIataForDate", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesByIataForDate {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iataCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int day;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string extendedOptions;
        
        public airlinesByIataForDate() {
        }
        
        public airlinesByIataForDate(string appId, string appKey, string iataCode, int year, int month, int day, string extendedOptions) {
            this.appId = appId;
            this.appKey = appKey;
            this.iataCode = iataCode;
            this.year = year;
            this.month = month;
            this.day = day;
            this.extendedOptions = extendedOptions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="airlinesByIataForDateResponse", WrapperNamespace="http://v1.airlines.cache.conducivetech.com/", IsWrapped=true)]
    public partial class airlinesByIataForDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://v1.airlines.cache.conducivetech.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return;
        
        public airlinesByIataForDateResponse() {
        }
        
        public airlinesByIataForDateResponse(WcfServiceFlightstats.ArlinesV1SoapService.airline[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface airlinesServiceChannel : WcfServiceFlightstats.ArlinesV1SoapService.airlinesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class airlinesServiceClient : System.ServiceModel.ClientBase<WcfServiceFlightstats.ArlinesV1SoapService.airlinesService>, WcfServiceFlightstats.ArlinesV1SoapService.airlinesService {
        
        public airlinesServiceClient() {
        }
        
        public airlinesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public airlinesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public airlinesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public airlinesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcaoResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlineByIcao(WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao request) {
            return base.Channel.airlineByIcao(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] airlineByIcao(string appId, string appKey, string icaoCode, int year, int month, int day, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.icaoCode = icaoCode;
            inValue.year = year;
            inValue.month = month;
            inValue.day = day;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcaoResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlineByIcao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcaoResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlineByIcaoAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao request) {
            return base.Channel.airlineByIcaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcaoResponse> airlineByIcaoAsync(string appId, string appKey, string icaoCode, int year, int month, int day, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlineByIcao();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.icaoCode = icaoCode;
            inValue.year = year;
            inValue.month = month;
            inValue.day = day;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlineByIcaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesByIata(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata request) {
            return base.Channel.airlinesByIata(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] airlinesByIata(string appId, string appKey, string iataCode, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.iataCode = iataCode;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesByIata(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesByIataAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata request) {
            return base.Channel.airlinesByIataAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataResponse> airlinesByIataAsync(string appId, string appKey, string iataCode, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIata();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.iataCode = iataCode;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesByIataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCodeResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlineByFsCode(WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode request) {
            return base.Channel.airlineByFsCode(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] airlineByFsCode(string appId, string appKey, string code, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.code = code;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCodeResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlineByFsCode(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCodeResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlineByFsCodeAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode request) {
            return base.Channel.airlineByFsCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCodeResponse> airlineByFsCodeAsync(string appId, string appKey, string code, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlineByFsCode();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.code = code;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlineByFsCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcaoResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesByIcao(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao request) {
            return base.Channel.airlinesByIcao(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] airlinesByIcao(string appId, string appKey, string icaoCode, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.icaoCode = icaoCode;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcaoResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesByIcao(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcaoResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesByIcaoAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao request) {
            return base.Channel.airlinesByIcaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcaoResponse> airlinesByIcaoAsync(string appId, string appKey, string icaoCode, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIcao();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.icaoCode = icaoCode;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesByIcaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.currentAirlinesResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.currentAirlines(WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines request) {
            return base.Channel.currentAirlines(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] currentAirlines(string appId, string appKey, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines inValue = new WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.currentAirlinesResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).currentAirlines(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.currentAirlinesResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.currentAirlinesAsync(WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines request) {
            return base.Channel.currentAirlinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.currentAirlinesResponse> currentAirlinesAsync(string appId, string appKey, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines inValue = new WcfServiceFlightstats.ArlinesV1SoapService.currentAirlines();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).currentAirlinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.allAirlinesResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.allAirlines(WcfServiceFlightstats.ArlinesV1SoapService.allAirlines request) {
            return base.Channel.allAirlines(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] allAirlines(string appId, string appKey, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.allAirlines inValue = new WcfServiceFlightstats.ArlinesV1SoapService.allAirlines();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.allAirlinesResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).allAirlines(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.allAirlinesResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.allAirlinesAsync(WcfServiceFlightstats.ArlinesV1SoapService.allAirlines request) {
            return base.Channel.allAirlinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.allAirlinesResponse> allAirlinesAsync(string appId, string appKey, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.allAirlines inValue = new WcfServiceFlightstats.ArlinesV1SoapService.allAirlines();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).allAirlinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlines(WcfServiceFlightstats.ArlinesV1SoapService.airlines request) {
            return base.Channel.airlines(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] airlines(string appId, string appKey, int year, int month, int day, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlines inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlines();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.year = year;
            inValue.month = month;
            inValue.day = day;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlines(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlines request) {
            return base.Channel.airlinesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesResponse> airlinesAsync(string appId, string appKey, int year, int month, int day, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlines inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlines();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.year = year;
            inValue.month = month;
            inValue.day = day;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDateResponse WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesByIataForDate(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate request) {
            return base.Channel.airlinesByIataForDate(request);
        }
        
        public WcfServiceFlightstats.ArlinesV1SoapService.airline[] airlinesByIataForDate(string appId, string appKey, string iataCode, int year, int month, int day, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.iataCode = iataCode;
            inValue.year = year;
            inValue.month = month;
            inValue.day = day;
            inValue.extendedOptions = extendedOptions;
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDateResponse retVal = ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesByIataForDate(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDateResponse> WcfServiceFlightstats.ArlinesV1SoapService.airlinesService.airlinesByIataForDateAsync(WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate request) {
            return base.Channel.airlinesByIataForDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDateResponse> airlinesByIataForDateAsync(string appId, string appKey, string iataCode, int year, int month, int day, string extendedOptions) {
            WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate inValue = new WcfServiceFlightstats.ArlinesV1SoapService.airlinesByIataForDate();
            inValue.appId = appId;
            inValue.appKey = appKey;
            inValue.iataCode = iataCode;
            inValue.year = year;
            inValue.month = month;
            inValue.day = day;
            inValue.extendedOptions = extendedOptions;
            return ((WcfServiceFlightstats.ArlinesV1SoapService.airlinesService)(this)).airlinesByIataForDateAsync(inValue);
        }
    }
}
